colorscheme desert

set tabpagemax=32

set guioptions-=T  "remove toolbar
" set guioptions-=m  "remove menu bar
" set guioptions-=r  "remove right-hand scroll bar
" set guioptions-=L  "remove left-hand scroll bar

